receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

processors:
  batch: {}
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - IsMatch(instrumentation_scope.name, "@opentelemetry/instrumentation-net")
        - IsMatch(instrumentation_scope.name, "@opentelemetry/instrumentation-dns")
  resource:
    attributes:
      - key: deployment.environment.name
        value: "dev"
        action: upsert

connectors:
  datadog/connector:
    traces:
      compute_stats_by_span_kind: true

exporters:
  debug:
  # verbosity: detailed
  datadog:
    traces:
      compute_stats_by_span_kind: true
    api:
      site: ${DD_SITE_PARAMETER}
      key: ${DD_API_KEY}
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/ottl, resource, batch]
      exporters: [debug, datadog/connector, datadog, otlp]
    metrics:
      receivers: [otlp, datadog/connector]
      processors: [filter/ottl, resource, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [filter/ottl, resource, batch]
      exporters: [datadog]
